# Introducción a SQL y Python II

In [ ]:
import numpy as np
import pandas as pd
import sqlite3

## Método para obtener los datos de una consulta

Se obtienen todas filas de una consulta (Query) en un DataFrame

In [ ]:
def get_data(cursor):
  all_rows = cursor.fetchall()
  column_names = [description[0] for description in cursor.description]
  df = pd.DataFrame(data=all_rows, columns = column_names)
  blankIndex=[''] * len(df)
  df.index=blankIndex
  return df

## Acceso Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# Colocar esta ruta
# ruta = "/content/drive/MyDrive/Colab Notebooks/"

ruta = "/content/drive/My Drive/Colab Notebooks/dip/ml/sqlite-pandas/"

## Consulta de Datos

In [ ]:
#@title Introducir Datos de un Empleado (Importante)

Nombre = 'Mercedez' #@param {type:"string"}
Edad   =  19#@param {type: 'integer'}
Ciudad =  'Cusco' #@param ["Arequipa", "Lima", "Cusco", "Puno", "Moquegua"]
Sueldo =  None#@param {type: 'integer'}

conn = sqlite3.connect(ruta+'BDEmpresas.db')

with conn:
  conn.execute("INSERT INTO EMPLEADO (NOMBRE, EDAD, CIUDAD, SUELDO) VALUES(?,?,?,?)",(Nombre, Edad, Ciudad, Sueldo))
conn.close()
print("Registro creado exitosamente!!")

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')

cursor = conn.execute("SELECT * FROM EMPLEADO")
df = get_data(cursor)

conn.close()
print("Operation done successfully")
df

In [ ]:
s = "1,hola"
s.split(",")

## Claúsula WHERE

Operador OR y AND

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')

cursor = conn.execute("SELECT * FROM EMPLEADO WHERE EDAD < 35 AND CIUDAD = 'Arequipa'")
df = get_data(cursor)

conn.close()
print("Operacion realizada exitosamente!!")
df

Operador DIFERENTE ($\texttt{!=}$)

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')

cursor = conn.execute("SELECT * FROM EMPLEADO WHERE CIUDAD=='Arequipa'")
df = get_data(cursor)

conn.close()
print("Operacion realizada exitosamente!!")
df

Forma facil de consultar con pandas y

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT * FROM EMPLEADO",conn)
conn.close()
datos

Operador IS NULL

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT * FROM EMPLEADO WHERE SUELDO IS NULL",conn)
conn.close()
print("Operacion realizada exitosamente!!")
datos

Operador IS NOT NULL

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT * FROM EMPLEADO WHERE SUELDO IS NOT NULL",conn)
conn.close()
print("Operacion realizada exitosamente!!")
datos

Operador LIKE

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT * FROM EMPLEADO WHERE NOMBRE LIKE 'Ma%'",conn)
conn.close()
print("Operacion realizada exitosamente!!")
datos

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT * FROM EMPLEADO WHERE CIUDAD LIKE '%ip%'",conn)
conn.close()
print("Operacion realizada exitosamente!!")
datos

Operador GLOB

Parecido a LIKE, pero usa patrones de expresiones regulares

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT * FROM EMPLEADO WHERE NOMBRE GLOB 'A*'",conn)
conn.close()
print("Operacion realizada exitosamente!!")
datos.head()

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT * FROM EMPLEADO WHERE EDAD GLOB '[0-9]*'",conn) # 0-9, a-z,
conn.close()
print("Operacion realizada exitosamente!!")
datos

Operador IN

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT * FROM EMPLEADO WHERE SUELDO IN (3000,5000)",conn)
conn.close()
print("Operacion realizada exitosamente!!")
datos

Operacion realizada exitosamente!!

   ID  NOMBRE  EDAD    CIUDAD  SUELDO
0   1   Pedro    30  Arequipa  3000.0
1   3   Maria    40  Arequipa  5000.0
2   5  Marcos    30  Arequipa  3000.0
3   6    Enzo    30  Arequipa  3000.0

Operador NOT IN

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT * FROM EMPLEADO WHERE EDAD NOT IN (30,60,40,25)",conn)
conn.close()
print("Operacion realizada exitosamente!!")
datos

Operacion realizada exitosamente!!

   ID     NOMBRE  EDAD    CIUDAD  SUELDO
0   4  Alejandro    23  Arequipa  1000.0
1   7       Luis    45      Lima  4500.0
2   8      Karen    38      Puno  7000.0
3   9       Luis    45      Lima  4500.0
4  10      Karen    34      Lima  4999.0
5  11       Jose    35      Lima  9000.0
6  13     Carlos    45  Moquegua  7000.0
7  16   Mercedez    19     Cusco     NaN

Operador BETWEEN

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT * FROM EMPLEADO WHERE EDAD BETWEEN 25 AND 35",conn)
conn.close()
print("Operacion realizada exitosamente!!")
datos

Operacion realizada exitosamente!!

   ID  NOMBRE  EDAD    CIUDAD  SUELDO
0   1   Pedro    30  Arequipa  3000.0
1   2    Juan    30  Arequipa  2000.0
2   5  Marcos    30  Arequipa  3000.0
3   6    Enzo    30  Arequipa  3000.0
4  10   Karen    34      Lima  4999.0
5  11    Jose    35      Lima  9000.0
6  14   Pedro    25     Cusco  8000.0
7  15   Pedro    25     Cusco     NaN

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT * FROM EMPLEADO WHERE EDAD IN (25,35)",conn)
conn.close()
print("Operacion realizada exitosamente!!")
datos

Operacion realizada exitosamente!!

   ID NOMBRE  EDAD CIUDAD  SUELDO
0  11   Jose    35   Lima  9000.0
1  14  Pedro    25  Cusco  8000.0
2  15  Pedro    25  Cusco     NaN

Operador EXISTS

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT * FROM EMPLEADO WHERE SUELDO > 4000",conn)
conn.close()
print("Operacion realizada exitosamente!!")
datos

Operacion realizada exitosamente!!

   ID  NOMBRE  EDAD    CIUDAD  SUELDO
0   3   Maria    40  Arequipa  5000.0
1   7    Luis    45      Lima  4500.0
2   8   Karen    38      Puno  7000.0
3   9    Luis    45      Lima  4500.0
4  10   Karen    34      Lima  4999.0
5  11    Jose    35      Lima  9000.0
6  12    Juan    60      Puno  8000.0
7  13  Carlos    45  Moquegua  7000.0
8  14   Pedro    25     Cusco  8000.0

Uso de una subconsulta (subquery)

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT * FROM EMPLEADO WHERE EDAD > 30",conn)
conn.close()
print("Operacion realizada exitosamente!!")
datos

Operacion realizada exitosamente!!

   ID  NOMBRE  EDAD    CIUDAD  SUELDO
0   3   Maria    40  Arequipa  5000.0
1   7    Luis    45      Lima  4500.0
2   8   Karen    38      Puno  7000.0
3   9    Luis    45      Lima  4500.0
4  10   Karen    34      Lima  4999.0
5  11    Jose    35      Lima  9000.0
6  12    Juan    60      Puno  8000.0
7  13  Carlos    45  Moquegua  7000.0

Operador DISTINCT

In [ ]:
# Con DISTINCT
conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT DISTINCT CIUDAD FROM EMPLEADO",conn)
conn.close()
print("Operacion realizada exitosamente!!")
datos

Operacion realizada exitosamente!!

     CIUDAD
0  Arequipa
1      Lima
2      Puno
3  Moquegua
4     Cusco

Operador LIMIT

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT * FROM EMPLEADO LIMIT 7",conn)
conn.close()
print("Operacion realizada exitosamente!!")
datos

Operacion realizada exitosamente!!

   ID     NOMBRE  EDAD    CIUDAD  SUELDO
0   1      Pedro    30  Arequipa  3000.0
1   2       Juan    30  Arequipa  2000.0
2   3      Maria    40  Arequipa  5000.0
3   4  Alejandro    23  Arequipa  1000.0
4   5     Marcos    30  Arequipa  3000.0
5   6       Enzo    30  Arequipa  3000.0
6   7       Luis    45      Lima  4500.0

Operador OFFSET

Indica desde donde debe leer los datos

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT * FROM EMPLEADO",conn)    ## Desde la posición 3
conn.close()
print("Operacion realizada exitosamente!!")
datos

Operacion realizada exitosamente!!

    ID     NOMBRE  EDAD    CIUDAD  SUELDO
0    1      Pedro    30  Arequipa  3000.0
1    2       Juan    30  Arequipa  2000.0
2    3      Maria    40  Arequipa  5000.0
3    4  Alejandro    23  Arequipa  1000.0
4    5     Marcos    30  Arequipa  3000.0
5    6       Enzo    30  Arequipa  3000.0
6    7       Luis    45      Lima  4500.0
7    8      Karen    38      Puno  7000.0
8    9       Luis    45      Lima  4500.0
9   10      Karen    34      Lima  4999.0
10  11       Jose    35      Lima  9000.0
11  12       Juan    60      Puno  8000.0
12  13     Carlos    45  Moquegua  7000.0
13  14      Pedro    25     Cusco  8000.0
14  15      Pedro    25     Cusco     NaN
15  16   Mercedez    19     Cusco     NaN

## Actualización de Información (UPDATE)

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')

with conn:
  conn.execute("UPDATE EMPLEADO SET SUELDO = 7000.00 WHERE ID = 3")
  print("Número total de columnas actualizadas: ", conn.total_changes)

conn.close()
print("Operacion realizada exitosamente!!")

Número total de columnas actualizadas:  1
Operacion realizada exitosamente!!

In [ ]:
## Datos actualizados

conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT ID, NOMBRE, CIUDAD, SUELDO FROM EMPLEADO",conn)
conn.close()
print("Operacion realizada exitosamente!!")
datos

Operacion realizada exitosamente!!

    ID     NOMBRE    CIUDAD  SUELDO
0    1      Pedro  Arequipa  3000.0
1    2       Juan  Arequipa  2000.0
2    3      Maria  Arequipa  7000.0
3    4  Alejandro  Arequipa  1000.0
4    5     Marcos  Arequipa  3000.0
5    6       Enzo  Arequipa  3000.0
6    7       Luis      Lima  4500.0
7    8      Karen      Puno  7000.0
8    9       Luis      Lima  4500.0
9   10      Karen      Lima  4999.0
10  11       Jose      Lima  9000.0
11  12       Juan      Puno  8000.0
12  13     Carlos  Moquegua  7000.0
13  14      Pedro     Cusco  8000.0
14  15      Pedro     Cusco     NaN
15  16   Mercedez     Cusco     NaN

## Eliminar Registros (DELETE)

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')

with conn:
  conn.execute("DELETE FROM EMPLEADO WHERE Ciudad = 'Cusco'")
  print("Número total de registros eliminados: ", conn.total_changes)

conn.close()

Número total de registros eliminados:  3

In [ ]:
## Datos actualizados

conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT ID, NOMBRE, CIUDAD, EDAD, SUELDO FROM EMPLEADO",conn)
conn.close()
print("Operacion realizada exitosamente!!")
datos

Operacion realizada exitosamente!!

   ID     NOMBRE    CIUDAD  EDAD  SUELDO
0   3      Maria  Arequipa    40  7000.0
1   4  Alejandro  Arequipa    23  1000.0
2   7       Luis      Lima    45  4500.0
3   8      Karen      Puno    38  7000.0
4   9       Luis      Lima    45  4500.0
5  10      Karen      Lima    34  4999.0
6  11       Jose      Lima    35  9000.0
7  12       Juan      Puno    60  8000.0
8  13     Carlos  Moquegua    45  7000.0

In [ ]:
try:
    conn = sqlite3.connect(ruta+'BDEmpresas.db')
    with conn:
        conn.execute("DELETE FROM EMPLEADO WHERE EDAD = 30")
        print("Número total de registros eliminados:", conn.total_changes)
except sqlite3.IntegrityError:
    print ("No es posible eliminar dos veces un registro!!!")

conn.close()

Número total de registros eliminados: 0

In [ ]:
## Datos actualizados

conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT * FROM EMPLEADO",conn)
conn.close()
print("Operacion realizada exitosamente!!")
datos

Operacion realizada exitosamente!!

   ID     NOMBRE  EDAD    CIUDAD  SUELDO
0   3      Maria    40  Arequipa  7000.0
1   4  Alejandro    23  Arequipa  1000.0
2   7       Luis    45      Lima  4500.0
3   8      Karen    38      Puno  7000.0
4   9       Luis    45      Lima  4500.0
5  10      Karen    34      Lima  4999.0
6  11       Jose    35      Lima  9000.0
7  12       Juan    60      Puno  8000.0
8  13     Carlos    45  Moquegua  7000.0

## Commit y Rollback

Commit

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')

conn.execute("INSERT INTO EMPLEADO (NOMBRE, EDAD, CIUDAD, SUELDO) VALUES ('Jorge', 55, 'Lima', 12000.00)")
conn.commit() # Confirmar
conn.close()
print("Registro creado exitosamente!!")

Registro creado exitosamente!!

In [ ]:
## CONSULTANDO
conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT ID, NOMBRE, EDAD, CIUDAD, SUELDO FROM EMPLEADO",conn)
conn.close()
print("Operacion realizada exitosamente!!")
datos

Operacion realizada exitosamente!!

    ID     NOMBRE  EDAD    CIUDAD   SUELDO
0    3      Maria    40  Arequipa   7000.0
1    4  Alejandro    23  Arequipa   1000.0
2    7       Luis    45      Lima   4500.0
3    8      Karen    38      Puno   7000.0
4    9       Luis    45      Lima   4500.0
5   10      Karen    34      Lima   4999.0
6   11       Jose    35      Lima   9000.0
7   12       Juan    60      Puno   8000.0
8   13     Carlos    45  Moquegua   7000.0
9   17       Jose    55      Lima  10000.0
10  18      Jorge    55      Lima  12000.0

Rollback

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')
conn.execute("INSERT INTO EMPLEADO (NOMBRE, EDAD, CIUDAD, SUELDO) VALUES ('Jorge', 55, 'Lima', 12000.00)")
conn.rollback()
conn.close()
print("Registro creado exitosamente!!")

Registro creado exitosamente!!

In [ ]:
## CONSULTANDO
conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT ID, NOMBRE, EDAD, CIUDAD, SUELDO FROM EMPLEADO",conn)
conn.close()
print("Operacion realizada exitosamente!!")
datos

Operacion realizada exitosamente!!

    ID     NOMBRE  EDAD    CIUDAD   SUELDO
0    3      Maria    40  Arequipa   7000.0
1    4  Alejandro    23  Arequipa   1000.0
2    7       Luis    45      Lima   4500.0
3    8      Karen    38      Puno   7000.0
4    9       Luis    45      Lima   4500.0
5   10      Karen    34      Lima   4999.0
6   11       Jose    35      Lima   9000.0
7   12       Juan    60      Puno   8000.0
8   13     Carlos    45  Moquegua   7000.0
9   17       Jose    55      Lima  10000.0
10  18      Jorge    55      Lima  12000.0

## ORDER BY

In [ ]:
## ASC
conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT * FROM EMPLEADO ORDER BY SUELDO ASC",conn)
conn.close()
print("Operacion realizada exitosamente!!")
datos

Operacion realizada exitosamente!!

    ID     NOMBRE  EDAD    CIUDAD   SUELDO
0    4  Alejandro    23  Arequipa   1000.0
1    7       Luis    45      Lima   4500.0
2    9       Luis    45      Lima   4500.0
3   10      Karen    34      Lima   4999.0
4    3      Maria    40  Arequipa   7000.0
5    8      Karen    38      Puno   7000.0
6   13     Carlos    45  Moquegua   7000.0
7   12       Juan    60      Puno   8000.0
8   11       Jose    35      Lima   9000.0
9   17       Jose    55      Lima  10000.0
10  18      Jorge    55      Lima  12000.0

In [ ]:
## DESC
conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT * FROM EMPLEADO ORDER BY SUELDO DESC",conn)
conn.close()
print("Operacion realizada exitosamente!!")
datos

Operacion realizada exitosamente!!

    ID     NOMBRE  EDAD    CIUDAD   SUELDO
0   18      Jorge    55      Lima  12000.0
1   17       Jose    55      Lima  10000.0
2   11       Jose    35      Lima   9000.0
3   12       Juan    60      Puno   8000.0
4    3      Maria    40  Arequipa   7000.0
5    8      Karen    38      Puno   7000.0
6   13     Carlos    45  Moquegua   7000.0
7   10      Karen    34      Lima   4999.0
8    7       Luis    45      Lima   4500.0
9    9       Luis    45      Lima   4500.0
10   4  Alejandro    23  Arequipa   1000.0

## Sentencia GROUP BY

Ejemplo GROUP BY

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT SUM(Sueldo) FROM EMPLEADO",conn)
conn.close()
print("Operacion realizada exitosamente!!")
datos

Operacion realizada exitosamente!!

   SUM(Sueldo)
0      74999.0

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT CIUDAD, SUM(SUELDO) FROM EMPLEADO GROUP BY CIUDAD",conn)
conn.close()
print("Operacion realizada exitosamente!!")
datos

Operacion realizada exitosamente!!

     CIUDAD  SUM(SUELDO)
0  Arequipa       8000.0
1      Lima      44999.0
2  Moquegua       7000.0
3      Puno      15000.0

GROUP BY y ORDER BY

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT CIUDAD, SUM(SUELDO), COUNT(*) FROM EMPLEADO GROUP BY CIUDAD ORDER BY CIUDAD",conn)
conn.close()
print("Operacion realizada exitosamente!!")
datos

Operacion realizada exitosamente!!

     CIUDAD  SUM(SUELDO)  COUNT(*)
0  Arequipa       8000.0         2
1      Lima      44999.0         6
2  Moquegua       7000.0         1
3      Puno      15000.0         2

## Claúsula HAVING

Uso de Count

In [ ]:
conn = sqlite3.connect(ruta+'BDEmpresas.db')
datos = pd.read_sql_query("SELECT CIUDAD, SUM(SUELDO), COUNT(*) FROM EMPLEADO GROUP BY CIUDAD HAVING COUNT(CIUDAD)>1",conn)  # > 1
conn.close()
print("Operacion realizada exitosamente!!")
datos

Operacion realizada exitosamente!!

     CIUDAD  SUM(SUELDO)  COUNT(*)
0  Arequipa       8000.0         2
1      Lima      44999.0         6
2      Puno      15000.0         2

# Ejercicio

Crear una TABLA y aplicar lo siguiente:

* Filtros
* Modificaciones a elementos
* Agrupar
* Ordenar